import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { EventLoggerPanel } from "@/components/EventLoggerPanel";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={geist.className}>
        {children}
        <EventLoggerPanel />
      </body>
    </html>
  );
}
